// Athena Login configuration file.

// Login server port.
login_port: 6900

// The login server listens on the interface with this IP address.
//bind_ip: 127.0.0.1

// Console Commands
console: off

// File path to store console messages.
console_log_filepath: ./log/login-msg_log.log

// Enable console log types.
console_msg_log: 0

// Console silent flags.
console_silent: 0

// Passwords in the login table are stored as MD5.
use_MD5_passwords: yes

// Login database connection
login_server_ip: 127.0.0.1
login_server_port: 3306
login_server_id: root
login_server_pw: VibeRO@2025!
login_server_db: ragnarok2026
login_case_sensitive: no

// IP ban database connection
ipban_db_ip: 127.0.0.1
ipban_db_port: 3306
ipban_db_id: root
ipban_db_pw: VibeRO@2025!
ipban_db_db: ragnarok2026

// Log database connection
log_db_ip: 127.0.0.1
log_db_port: 3306
log_db_id: root
log_db_pw: VibeRO@2025!
log_db_db: log2025

// Imports
import: conf/import/login_conf.txt
