// Subnet support file
// Format is:
// subnet: net-submask:char_ip:map_ip
// you can add more than one subnet (max 16)
// check is if((net-submask & char_ip ) == (net-submask & servip)) => ok

// Restrict to only allow connections from the server itself and public IP
subnet: 127.0.0.0:255.0.0.0:vibe-r-online.com:vibe-r-online.com
subnet: vibe-r-online.com:255.255.255.255:vibe-r-online.com:vibe-r-online.com
