// Athena Web configuration file.

// Bind IP for the web server.
bind_ip: 0.0.0.0

// Port used by the web server.
web_port: 8888

// File path to store console messages.
console_log_filepath: ./log/web-msg_log.log

// Enable console log types.
console_msg_log: 0

// Console silent flags.
console_silent: 0

// Imports
import: conf/import/web_conf.txt
