CREATE TABLE IF NOT EXISTS `mvp_card_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `drop_date` datetime NOT NULL,
  `account_id` int(11) unsigned NOT NULL DEFAULT '0',
  `char_id` int(11) unsigned NOT NULL DEFAULT '0',
  `char_name` varchar(25) NOT NULL DEFAULT '',
  `monster_id` smallint(6) unsigned NOT NULL DEFAULT '0',
  `monster_name` varchar(50) NOT NULL DEFAULT '',
  `card_id` int(10) unsigned NOT NULL DEFAULT '0',
  `card_name` varchar(50) NOT NULL DEFAULT '',
  `drop_rate` int(11) NOT NULL DEFAULT '0',
  `map` varchar(11) NOT NULL DEFAULT '',
  `x` smallint(5) unsigned NOT NULL DEFAULT '0',
  `y` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX (`drop_date`),
  INDEX (`account_id`),
  INDEX (`char_id`),
  INDEX (`monster_id`),
  INDEX (`card_id`)
) ENGINE=MyISAM;
