CREATE TABLE IF NOT EXISTS `shop_transactions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `account_id` int(11) unsigned NOT NULL DEFAULT '0',
  `char_id` int(11) unsigned NOT NULL DEFAULT '0',
  `char_name` varchar(25) NOT NULL DEFAULT '',
  `map` varchar(11) NOT NULL DEFAULT '',
  `npc_name` varchar(50) NOT NULL DEFAULT '',
  `shop_name` varchar(50) NOT NULL DEFAULT '',
  `source` varchar(31) NOT NULL DEFAULT '',
  `item_id` int(10) unsigned NOT NULL DEFAULT '0',
  `item_name` varchar(50) NOT NULL DEFAULT '',
  `amount` int(10) unsigned NOT NULL DEFAULT '0',
  `zeny` int(11) NOT NULL DEFAULT '0',
  `required_item_id` int(10) unsigned NOT NULL DEFAULT '0',
  `required_item_name` varchar(50) NOT NULL DEFAULT '',
  `required_item_amount` int(10) unsigned NOT NULL DEFAULT '0',
  `point_type` varchar(31) NOT NULL DEFAULT '',
  `point_amount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX (`time`),
  INDEX (`account_id`),
  INDEX (`char_id`),
  INDEX (`shop_name`),
  INDEX (`source`),
  INDEX (`item_id`)
) ENGINE=MyISAM;
